# src/main/resources/application.yml
spring:
  application:
    name: space-global
  
  datasource:
    url: jdbc:postgresql://localhost:5432/space_global
    username: postgres
    password: Aa1234
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  
  cache:
    type: redis
    redis:
      time-to-live: 3600000 # 1 hour
  
  data:
    redis:
        host: localhost
        port: 6379

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:P8r5Yd2jKsTqA9zBnXv6wU3mCeFgHkLpR7xW1oJ0iN4sSyDtZuQ5bGcVfM8aEl7h}
  expiration: 86400000 # 24 hours

# AWS S3 Configuration
aws:
  s3:
    bucket: ${AWS_S3_BUCKET:space-global-images}
    region: ${AWS_REGION:us-east-1}
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api

# Logging Configuration
logging:
  level:
    com.space_global: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
